### ISSUE TITLE
Experiment w/ pangeo-forge

### ISSUE THREAD

**Issue by mfisher87** [QGreenland-Net/.github#3]
Working in: https://github.com/QGreenland-Net/pangeo-forge-exploration

**Comment by trey-stafford** [comment]
We ran into a blocker w/ trying to use the `pange-forge-runner` to write data to a local directory specified by the runner config. 

The runner code is written to specifically inject the config into the Zarr-specific writer transforms written in `pangeo-forge-recipes`.  There is currently not a way to write a "generic" writer transform that accepts runner config (e.g., `c.TargetStorage.root_path`) without modifying the `pangeo-forge-runner` plugin code. See: https://github.com/pangeo-forge/pangeo-forge-runner/blob/167b565fe70276793ba7761b0f3a39a768eaea3a/pangeo_forge_runner/plugin.py#L124-L136

**Comment by trey-stafford** [comment]
We got to a stopping point where we fetch data from the ADC (a CSV) with location data from seal tag observations and convert that into a GeoPackage.

**Comment by mfisher87** [comment]
However, we're writing our geopackage to the root directory of the repository instead of to the correct pangeo forge configured output location. We've worked with Pangeo Forge folks and learned of a workaround, but we need to document it. That task is captured here:

https://github.com/QGreenland-Net/pangeo-forge-exploration/issues/1
