### ISSUE TITLE
Schedule and have dedicated discussion about OGDC design

### ISSUE THREAD

**Issue by trey-stafford** [QGreenland-Net/.github#32]
Discuss design/architecture of OGDC. This meeting should be longer than 1 hour in length to give us plenty of time to talk about various components, interfaces, and API design (https://github.com/QGreenland-Net/.github/issues/33) for the OGDC.

Discussion should be driven by list of core functions developed in QGreenland-Net/qgreenland-net.github.io#40 .

Depends on sharing outcome of QGreenland-Net/.github#26 + specific questions / feedback points we want ADC folks to think about.

**Comment by mfisher87** [comment]
Meeting happened today https://docs.google.com/document/d/1ZcTcmVtUSjyWAy0TWnTWEWQ4Y2gqhub0yNaqVwpKxDY/edit
