### ISSUE TITLE
Add Matt and Trey to ADC dev k8s cluster allow-list

### ISSUE THREAD

**Issue by mfisher87** [QGreenland-Net/.github#6]
- [x] @mfisher87 @trey-stafford provide @rushirajnenuji with stable IP addresses to add to allow-list
- [ ] @rushirajnenuji to request / add us to the list on ADC side

**Comment by rushirajnenuji** [comment]
Yesterday, Matt Jones and Matthew Brooke helped set up the firewall access to our IPs. All three of us should have access. Moving this to review until we can all verify and confirm the access.

**Comment by rushirajnenuji** [comment]
confirmed access, closing this as done
