### ISSUE TITLE
Set up namespace for QGreenland work in ADC dev k8s cluster

### ISSUE THREAD

**Issue by mfisher87** [QGreenland-Net/.github#7]
- [x] @rushirajnenuji check if he has access to `k8s-dev`
- [x] @rushirajnenuji create new `qgnet` service account and namespace, see <https://github.com/DataONEorg/k8s-cluster/tree/main/authorization>

**Comment by rushirajnenuji** [comment]
qgnet namespace is created on the k8s dev cluster running at NCEAS / DataONE. 
config files have been shared with the devs.

Next steps:
- [ ] verify access to namespace

**Comment by mfisher87** [comment]
Maybe we could just close this one, since #6 covers verifying remote access. What do you think?

**Comment by rushirajnenuji** [comment]
confirmed access, closing this as done
