### ISSUE TITLE
"Hello world" on ADC dev k8s cluster

### ISSUE THREAD

**Issue by mfisher87** [QGreenland-Net/.github#8]
Some documentation on GH that can help getting started: <https://github.com/dataoneorg/k8s-cluster>

**Comment by trey-stafford** [comment]
We were able to deploy a "hello world" example on ADC's k8s cluster using helm. We deployed an nginx container that we were able to port-forward to our local machines.

See: https://github.com/QGreenland-Net/adc-k8s-deploy-exploration
